version: "3"

services:
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "app.app:create_app()"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes: 
      - ".:/app"