---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "point-of-sale-api-config-fbhh"
  namespace: "default"
  labels:
    app: "point-of-sale-api"
data:
  someenv: "crazyvalue"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "point-of-sale-api"
  namespace: "default"
  labels:
    app: "point-of-sale-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "point-of-sale-api"
  template:
    metadata:
      labels:
        app: "point-of-sale-api"
    spec:
      containers:
      - name: "image-sha256-1"
        image: "northamerica-northeast2-docker.pkg.dev/point-of-sale-329816/point-of-sale-api/image@sha256:97f23bf4217092bca17411c3383a0adc9a19927151a458a982c615c3b32f7fc9"
        env:
        - name: "someenv"
          valueFrom:
            configMapKeyRef:
              key: "someenv"
              name: "point-of-sale-api-config-fbhh"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "point-of-sale-api-hpa-bl5x"
  namespace: "default"
  labels:
    app: "point-of-sale-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "point-of-sale-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80